import json

specs = [
  {
    "number": 1,
    "id": "dglobal-batch10-div-01",
    "slug": "div10_01_aliwong",
    "comedian": "Ali Wong",
    "title": "RELATIONSHIPS · Auntie Ali & Bossy Girls · Ali Wong · DressIt",
    "topic": "Bossy Girls & Relationship Advice",
    "standup_clip": {
      "source_file": "/root/dressit-pipeline/source_clips/MF-8f7wpgxU.mp4",
      "cut1_ss": 18.5,
      "cut1_dur": 3.5,
      "cut1_crop": "crop=540:960:665:0,scale=1080:1920:flags=lanczos",
      "cut2_ss": 22.0,
      "cut2_dur": 4.5,
      "cut2_crop": "crop=540:960:665:0,scale=1080:1920:flags=lanczos",
      "standup_dur": 8.0,
      "setup_quote": "Auntie Ali, break up with her. She is crazy.",
      "punchline_quote": "And I said: I do not mind crazy girls. I like when girls boss me around!"
    },
    "ugc_cut_a": "/root/event-hero/assets/maria_ugc/maria_01_angaevamariia_vid_qYVNgIgi.mp4",
    "ugc_cut_a_ss": 2.0,
    "ugc_cut_a_dur": 3.6,
    "ugc_cut_b": "/root/event-hero/assets/maria_ugc/maria_04_angaevamariia_vid_28hF5F0z.mp4",
    "ugc_cut_b_ss": 1.5,
    "ugc_cut_b_dur": 7.0,
    "audio_asset": "/root/dressit-pipeline/assets/voice_div10_01_aliwong.mp3",
    "voiceover_script": "Skip the bossy relationship drama completely. Post your dream outfit on DressIt and let sweet guys fund it for free at dressitnow.com!",
    "audio_duration_sec": 10.08,
    "caption": "I like when girls boss me around! 😂 Skip the relationship drama: post your dream outfit on DressIt and let sweet guys fund it for $0! dressitnow.com ✨\n\n#dating #aliwong #standup #relationships #datingadvice #freedress #dressit",
    "dialogue": [
      {"start": "0:00:00.00", "end": "0:00:01.60", "text": "AUNTIE ALI,"},
      {"start": "0:00:01.60", "end": "0:00:03.40", "text": "BREAK UP WITH HER!"},
      {"start": "0:00:03.50", "end": "0:00:05.20", "text": "SHE IS CRAZY!"},
      {"start": "0:00:05.20", "end": "0:00:06.60", "text": "AND I SAID:"},
      {"start": "0:00:06.60", "end": "0:00:07.80", "text": "I DO NOT MIND CRAZY GIRLS!"},
      {"start": "0:00:07.80", "end": "0:00:09.50", "text": "I LIKE WHEN GIRLS\nBOSS ME AROUND!"},
      {"start": "0:00:08.20", "end": "0:00:10.50", "text": "SKIP THE BOSSY\nRELATIONSHIP DRAMA!"},
      {"start": "0:00:10.50", "end": "0:00:13.00", "text": "POST YOUR DREAM OUTFIT\nON DRESSIT..."},
      {"start": "0:00:13.00", "end": "0:00:15.50", "text": "AND LET SWEET GUYS\nFUND IT FOR FREE!"},
      {"start": "0:00:15.50", "end": "0:00:18.00", "text": "DRESSITNOW.COM"}
    ]
  },
  {
    "number": 2,
    "id": "dglobal-batch10-div-02",
    "slug": "div10_02_iliza",
    "comedian": "Iliza Shlesinger",
    "title": "RELATIONSHIPS · Halfway Decent Advice · Iliza Shlesinger · DressIt",
    "topic": "Girl Dating Advice & Low Effort Boys",
    "standup_clip": {
      "source_file": "/root/dressit-pipeline/source_clips/XCQ-vMN9b4s.mp4",
      "cut1_ss": 0.5,
      "cut1_dur": 4.0,
      "cut1_crop": "crop=540:960:918:0,scale=1080:1920:flags=lanczos",
      "cut2_ss": 4.5,
      "cut2_dur": 4.5,
      "cut2_crop": "crop=540:960:723:0,scale=1080:1920:flags=lanczos",
      "standup_dur": 8.5,
      "setup_quote": "Wisdom nuggets that girls have that they will pass down to you...",
      "punchline_quote": "...that are so basic and halfway decent, but you are only hearing half the problem!"
    },
    "ugc_cut_a": "/root/event-hero/assets/maria_ugc/maria_02_angaevamariia_vid_yA0F4Nfg.mp4",
    "ugc_cut_a_ss": 1.0,
    "ugc_cut_a_dur": 3.6,
    "ugc_cut_b": "/root/event-hero/assets/maria_ugc/maria_06_angaevamariia_vid_YhozXb0A.mp4",
    "ugc_cut_b_ss": 1.5,
    "ugc_cut_b_dur": 7.5,
    "audio_asset": "/root/dressit-pipeline/assets/voice_div10_02_iliza.mp3",
    "voiceover_script": "Tired of low effort hey texts from guys? Post your dream dress on DressIt and let men who actually show effort fund it for free at dressitnow.com!",
    "audio_duration_sec": 10.73,
    "caption": "Wisdom nuggets are only half the story! 💁‍♀️ Tired of low-effort boys? Post your dream dress on DressIt and let guys who show effort fund it for $0! dressitnow.com ✨\n\n#dating #ilizashlesinger #standup #datingstandards #postyouroutfit #freedress #dressit",
    "dialogue": [
      {"start": "0:00:00.00", "end": "0:00:02.00", "text": "WISDOM NUGGETS"},
      {"start": "0:00:02.00", "end": "0:00:04.00", "text": "THAT GIRLS HAVE..."},
      {"start": "0:00:04.00", "end": "0:00:06.20", "text": "THAT THEY PASS DOWN\nTO YOU..."},
      {"start": "0:00:06.20", "end": "0:00:08.50", "text": "ARE SO BASIC,\nAND HALFWAY DECENT!"},
      {"start": "0:00:08.50", "end": "0:00:11.00", "text": "BUT YOU ARE ONLY HEARING\nHALF THE PROBLEM!"},
      {"start": "0:00:08.70", "end": "0:00:11.20", "text": "TIRED OF LOW EFFORT\nHEY TEXTS FROM GUYS?"},
      {"start": "0:00:11.20", "end": "0:00:13.80", "text": "POST YOUR DREAM DRESS\nON DRESSIT..."},
      {"start": "0:00:13.80", "end": "0:00:16.80", "text": "AND LET MEN WHO SHOW EFFORT\nFUND IT FOR FREE!"},
      {"start": "0:00:16.80", "end": "0:00:19.20", "text": "DRESSITNOW.COM"}
    ]
  },
  {
    "number": 3,
    "id": "dglobal-batch10-div-03",
    "slug": "div10_03_fortune",
    "comedian": "Fortune Feimster",
    "title": "RELATIONSHIPS · Ashley Davidson & The Minivan · Fortune Feimster · DressIt",
    "topic": "Mom Dating Expectations & Ashley Davidson",
    "standup_clip": {
      "source_file": "/root/dressit-shorts/clips/d3hy_XNU458.mp4",
      "cut1_ss": 10.8,
      "cut1_dur": 4.2,
      "cut1_crop": "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920:(in_w-1080)/2:(in_h-1920)/2",
      "cut2_ss": 15.0,
      "cut2_dur": 4.2,
      "cut2_crop": "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920:(in_w-1080)/2:(in_h-1920)/2",
      "standup_dur": 8.4,
      "setup_quote": "My mom calls and she is like: Do you remember Ashley Davidson?",
      "punchline_quote": "Well, she is married now, Fortune! She has got two kids and a minivan!"
    },
    "ugc_cut_a": "/root/event-hero/assets/maria_ugc/maria_03_angaevamariia_vid_1hWvR6y7.mp4",
    "ugc_cut_a_ss": 2.0,
    "ugc_cut_a_dur": 3.6,
    "ugc_cut_b": "/root/event-hero/assets/maria_ugc/maria_01_angaevamariia_vid_qYVNgIgi.mp4",
    "ugc_cut_b_ss": 1.5,
    "ugc_cut_b_dur": 7.8,
    "audio_asset": "/root/dressit-pipeline/assets/voice_div10_03_fortune.mp3",
    "voiceover_script": "You do not need to be Ashley Davidson to get the best wardrobe. Post your favorite dress on DressIt and let generous guys fund it for free at dressitnow.com!",
    "audio_duration_sec": 11.09,
    "caption": "Mom, I do not want a minivan! 😂 You do not need to be Ashley Davidson to dress amazing: post your dream outfit on DressIt and let generous guys fund it for $0! dressitnow.com ✨\n\n#dating #fortunefeimster #standup #relationships #familypressure #freedress #dressit",
    "dialogue": [
      {"start": "0:00:00.00", "end": "0:00:02.20", "text": "MY MOM CALLS..."},
      {"start": "0:00:02.20", "end": "0:00:04.20", "text": "AND SHE IS LIKE:"},
      {"start": "0:00:04.20", "end": "0:00:06.20", "text": "DO YOU REMEMBER\nASHLEY DAVIDSON?"},
      {"start": "0:00:06.20", "end": "0:00:08.40", "text": "WELL SHE IS MARRIED NOW,\nFORTUNE!"},
      {"start": "0:00:08.40", "end": "0:00:11.00", "text": "SHE HAS GOT TWO KIDS\nAND A MINIVAN!"},
      {"start": "0:00:08.60", "end": "0:00:11.80", "text": "YOU DO NOT NEED TO BE ASHLEY\nTO GET THE BEST WARDROBE!"},
      {"start": "0:00:11.80", "end": "0:00:14.50", "text": "POST YOUR FAVORITE DRESS\nON DRESSIT..."},
      {"start": "0:00:14.50", "end": "0:00:17.20", "text": "AND LET GENEROUS GUYS\nFUND IT FOR FREE!"},
      {"start": "0:00:17.20", "end": "0:00:19.50", "text": "DRESSITNOW.COM"}
    ]
  },
  {
    "number": 4,
    "id": "dglobal-batch10-div-04",
    "slug": "div10_04_ianlara",
    "comedian": "Ian Lara",
    "title": "RELATIONSHIPS · Dating Me Is Like Bitcoin · Ian Lara · DressIt",
    "topic": "Dating Potential & Investment",
    "standup_clip": {
      "source_file": "/root/dressit-shorts/clips/VP2GWZomhE8.mp4",
      "cut1_ss": 4.2,
      "cut1_dur": 4.0,
      "cut1_crop": "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920:(in_w-1080)/2:(in_h-1920)/2",
      "cut2_ss": 8.2,
      "cut2_dur": 4.4,
      "cut2_crop": "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920:(in_w-1080)/2:(in_h-1920)/2",
      "standup_dur": 8.4,
      "setup_quote": "Dating me right now is like buying Bitcoin in 2011...",
      "punchline_quote": "It is a little risky right now, but the stock is going straight up!"
    },
    "ugc_cut_a": "/root/event-hero/assets/maria_ugc/maria_04_angaevamariia_vid_28hF5F0z.mp4",
    "ugc_cut_a_ss": 1.5,
    "ugc_cut_a_dur": 3.6,
    "ugc_cut_b": "/root/event-hero/assets/maria_ugc/maria_02_angaevamariia_vid_yA0F4Nfg.mp4",
    "ugc_cut_b_ss": 2.0,
    "ugc_cut_b_dur": 7.0,
    "audio_asset": "/root/dressit-pipeline/assets/voice_div10_04_ianlara.mp3",
    "voiceover_script": "Invest in someone who actually invests in you. Post your style on DressIt and let quality guys fund your outfits for free at dressitnow.com!",
    "audio_duration_sec": 9.98,
    "caption": "Dating me is like Bitcoin in 2011 📈 Invest in guys who actually invest in you: post your style on DressIt and get funded for $0! dressitnow.com ✨\n\n#dating #ianlara #standup #comedycellar #investinyourself #freedress #dressit",
    "dialogue": [
      {"start": "0:00:00.00", "end": "0:00:02.00", "text": "DATING ME RIGHT NOW..."},
      {"start": "0:00:02.00", "end": "0:00:04.00", "text": "IS LIKE BUYING BITCOIN\nIN 2011!"},
      {"start": "0:00:04.00", "end": "0:00:06.00", "text": "IT IS A LITTLE RISKY\nRIGHT NOW..."},
      {"start": "0:00:06.00", "end": "0:00:08.40", "text": "BUT THE STOCK IS GOING\nSTRAIGHT UP!"},
      {"start": "0:00:08.60", "end": "0:00:11.20", "text": "INVEST IN SOMEONE WHO\nINVESTS IN YOU!"},
      {"start": "0:00:11.20", "end": "0:00:13.80", "text": "POST YOUR STYLE\nON DRESSIT..."},
      {"start": "0:00:13.80", "end": "0:00:16.50", "text": "AND LET QUALITY GUYS\nFUND YOUR OUTFITS FREE!"},
      {"start": "0:00:16.50", "end": "0:00:18.40", "text": "DRESSITNOW.COM"}
    ]
  },
  {
    "number": 5,
    "id": "dglobal-batch10-div-05",
    "slug": "div10_05_nate",
    "comedian": "Nate Bargatze",
    "title": "RELATIONSHIPS · What Marriage Feels Like · Nate Bargatze · DressIt",
    "topic": "Marriage Dynamics & Good Guys",
    "standup_clip": {
      "source_file": "/root/dressit-shorts/clips/wacNJSgPxUM.mp4",
      "cut1_ss": 0.2,
      "cut1_dur": 3.6,
      "cut1_crop": "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920:(in_w-1080)/2:(in_h-1920)/2",
      "cut2_ss": 3.8,
      "cut2_dur": 4.4,
      "cut2_crop": "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920:(in_w-1080)/2:(in_h-1920)/2",
      "standup_dur": 8.0,
      "setup_quote": "My wife and I were talking about what marriage feels like...",
      "punchline_quote": "And she goes: It feels like you are trapped, but in a good way! And I said: Get out of here!"
    },
    "ugc_cut_a": "/root/event-hero/assets/maria_ugc/maria_06_angaevamariia_vid_YhozXb0A.mp4",
    "ugc_cut_a_ss": 1.5,
    "ugc_cut_a_dur": 3.6,
    "ugc_cut_b": "/root/event-hero/assets/maria_ugc/maria_03_angaevamariia_vid_1hWvR6y7.mp4",
    "ugc_cut_b_ss": 2.0,
    "ugc_cut_b_dur": 7.0,
    "audio_asset": "/root/dressit-pipeline/assets/voice_div10_05_nate.mp3",
    "voiceover_script": "Leave all that awkward ex energy in the past. Post your favorite outfit on DressIt and let good guys fund it with zero drama at dressitnow.com!",
    "audio_duration_sec": 10.08,
    "caption": "Trapped in a good way?! 😂 Skip the drama and connect with good guys: post your favorite outfit on DressIt and get it funded for $0! dressitnow.com ✨\n\n#dating #natebargatze #standup #marriagehumor #relationships #freedress #dressit",
    "dialogue": [
      {"start": "0:00:00.00", "end": "0:00:01.80", "text": "MY WIFE AND I..."},
      {"start": "0:00:01.80", "end": "0:00:03.60", "text": "WERE TALKING ABOUT\nWHAT MARRIAGE FEELS LIKE."},
      {"start": "0:00:03.60", "end": "0:00:05.80", "text": "AND SHE GOES:\nIT FEELS LIKE YOU ARE TRAPPED..."},
      {"start": "0:00:05.80", "end": "0:00:08.00", "text": "...BUT IN A GOOD WAY!"},
      {"start": "0:00:08.00", "end": "0:00:10.00", "text": "AND I SAID:\nGET OUT OF HERE!"},
      {"start": "0:00:08.20", "end": "0:00:11.00", "text": "LEAVE ALL THAT AWKWARD\nEX ENERGY IN THE PAST!"},
      {"start": "0:00:11.00", "end": "0:00:13.50", "text": "POST YOUR FAVORITE OUTFIT\nON DRESSIT..."},
      {"start": "0:00:13.50", "end": "0:00:16.00", "text": "AND LET GOOD GUYS FUND IT\nWITH ZERO DRAMA!"},
      {"start": "0:00:16.00", "end": "0:00:18.10", "text": "DRESSITNOW.COM"}
    ]
  },
  {
    "number": 6,
    "id": "dglobal-batch10-div-06",
    "slug": "div10_06_taylor",
    "comedian": "Taylor Tomlinson",
    "title": "RELATIONSHIPS · I Quit Dating Losers · Taylor Tomlinson · DressIt",
    "topic": "Dating Standards & Settling",
    "standup_clip": {
      "source_file": "/root/dressit-shorts/clips/oagNYHB3Kzk.mp4",
      "cut1_ss": 4.2,
      "cut1_dur": 2.35,
      "cut1_crop": "crop=540:960:519:0,scale=1080:1920:flags=lanczos",
      "cut2_ss": 6.55,
      "cut2_dur": 6.05,
      "cut2_crop": "crop=540:960:613:0,scale=1080:1920:flags=lanczos",
      "standup_dur": 8.4,
      "setup_quote": "I have done so much work on myself in the last 5 years:",
      "punchline_quote": "I quit dating losers! That took a minute. There is no rehab for that!"
    },
    "ugc_cut_a": "/root/event-hero/assets/maria_ugc/maria_01_angaevamariia_vid_qYVNgIgi.mp4",
    "ugc_cut_a_ss": 2.0,
    "ugc_cut_a_dur": 3.6,
    "ugc_cut_b": "/root/event-hero/assets/maria_ugc/maria_04_angaevamariia_vid_28hF5F0z.mp4",
    "ugc_cut_b_ss": 1.5,
    "ugc_cut_b_dur": 6.5,
    "audio_asset": "/root/dressit-pipeline/assets/voice_div10_06_taylor.mp3",
    "voiceover_script": "Stop settling for guys who put in zero effort. Post your dream outfit on DressIt and let good guys fund it for free at dressitnow.com!",
    "audio_duration_sec": 9.10,
    "caption": "I quit dating losers — that took a minute! 💅 Stop settling for low-effort boys: post your dream outfit on DressIt and let good guys fund it for $0! dressitnow.com ✨\n\n#dating #taylortomlinson #standup #datingstandards #postyouroutfit #freedress #dressit",
    "dialogue": [
      {"start": "0:00:00.00", "end": "0:00:02.35", "text": "I HAVE DONE SO MUCH WORK\nON MYSELF IN 5 YEARS:"},
      {"start": "0:00:02.35", "end": "0:00:04.50", "text": "I QUIT DATING LOSERS!"},
      {"start": "0:00:04.50", "end": "0:00:06.00", "text": "THAT TOOK A MINUTE!"},
      {"start": "0:00:06.00", "end": "0:00:08.40", "text": "THERE IS NO REHAB\nFOR THAT!"},
      {"start": "0:00:08.60", "end": "0:00:11.00", "text": "STOP SETTLING FOR GUYS\nWITH ZERO EFFORT!"},
      {"start": "0:00:11.00", "end": "0:00:13.40", "text": "POST YOUR DREAM OUTFIT\nON DRESSIT..."},
      {"start": "0:00:13.40", "end": "0:00:15.60", "text": "AND LET GOOD GUYS\nFUND IT FOR FREE!"},
      {"start": "0:00:15.60", "end": "0:00:17.50", "text": "DRESSITNOW.COM"}
    ]
  },
  {
    "number": 7,
    "id": "dglobal-batch10-div-07",
    "slug": "div10_07_mattrife",
    "comedian": "Matt Rife",
    "title": "RELATIONSHIPS · Red Flags & Gym Girls · Matt Rife · DressIt",
    "topic": "Red Flags & Girl Resting",
    "standup_clip": {
      "source_file": "/root/dressit-pipeline/source_clips/Xe9ycTBoX94.mp4",
      "cut1_ss": 22.2,
      "cut1_dur": 3.6,
      "cut1_crop": "crop=540:960:685:0,scale=1080:1920:flags=lanczos",
      "cut2_ss": 25.8,
      "cut2_dur": 4.7,
      "cut2_crop": "crop=540:960:842:0,scale=1080:1920:flags=lanczos",
      "standup_dur": 8.3,
      "setup_quote": "A guy said: It is a red flag if a girl does not go to the gym.",
      "punchline_quote": "I was like: Bro, that is not a red flag, that is just a girl resting! Leave her alone!"
    },
    "ugc_cut_a": "/root/event-hero/assets/maria_ugc/maria_02_angaevamariia_vid_yA0F4Nfg.mp4",
    "ugc_cut_a_ss": 1.0,
    "ugc_cut_a_dur": 3.6,
    "ugc_cut_b": "/root/event-hero/assets/maria_ugc/maria_06_angaevamariia_vid_YhozXb0A.mp4",
    "ugc_cut_b_ss": 1.5,
    "ugc_cut_b_dur": 7.5,
    "audio_asset": "/root/dressit-pipeline/assets/voice_div10_07_mattrife.mp3",
    "voiceover_script": "Say goodbye to red flag drama once and for all. Post your style on DressIt and meet green flag guys who fund your outfits for free at dressitnow.com!",
    "audio_duration_sec": 10.39,
    "caption": "Bro, she is just resting! 💅 Leave red flags behind and meet green flag guys: post your style on DressIt and let them fund it for $0! dressitnow.com ✨\n\n#dating #mattrife #standup #redflags #greenflags #freedress #dressit",
    "dialogue": [
      {"start": "0:00:00.00", "end": "0:00:01.80", "text": "A GUY SAID:"},
      {"start": "0:00:01.80", "end": "0:00:03.60", "text": "IT IS A RED FLAG IF A GIRL\nDOES NOT GO TO THE GYM!"},
      {"start": "0:00:03.60", "end": "0:00:05.50", "text": "I WAS LIKE: BRO,\nTHAT IS NOT A RED FLAG!"},
      {"start": "0:00:05.50", "end": "0:00:07.00", "text": "THAT IS JUST A GIRL\nRESTING!"},
      {"start": "0:00:07.00", "end": "0:00:08.30", "text": "LEAVE HER ALONE!"},
      {"start": "0:00:08.50", "end": "0:00:11.20", "text": "SAY GOODBYE TO RED FLAG\nDRAMA ONCE AND FOR ALL!"},
      {"start": "0:00:11.20", "end": "0:00:14.00", "text": "POST YOUR STYLE ON DRESSIT..."},
      {"start": "0:00:14.00", "end": "0:00:16.80", "text": "AND MEET GREEN FLAG GUYS\nWHO FUND YOUR OUTFITS FREE!"},
      {"start": "0:00:16.80", "end": "0:00:18.80", "text": "DRESSITNOW.COM"}
    ]
  },
  {
    "number": 8,
    "id": "dglobal-batch10-div-08",
    "slug": "div10_08_jokoy",
    "comedian": "Jo Koy",
    "title": "RELATIONSHIPS · What is Under The Couch · Jo Koy · DressIt",
    "topic": "Family Stress & Dating Expectations",
    "standup_clip": {
      "source_file": "/root/dressit-pipeline/source_clips/_g4nWEyCW_o.mp4",
      "cut1_ss": 17.5,
      "cut1_dur": 4.0,
      "cut1_crop": "crop=540:960:692:0,scale=1080:1920:flags=lanczos",
      "cut2_ss": 21.5,
      "cut2_dur": 4.5,
      "cut2_crop": "crop=540:960:692:0,scale=1080:1920:flags=lanczos",
      "standup_dur": 8.5,
      "setup_quote": "Normal parents help their kids find stuff when they lose it. Not my mom!",
      "punchline_quote": "If I am looking under the couch, she is right behind me: Oh! What is under the couch?!"
    },
    "ugc_cut_a": "/root/event-hero/assets/maria_ugc/maria_03_angaevamariia_vid_1hWvR6y7.mp4",
    "ugc_cut_a_ss": 2.0,
    "ugc_cut_a_dur": 3.6,
    "ugc_cut_b": "/root/event-hero/assets/maria_ugc/maria_01_angaevamariia_vid_qYVNgIgi.mp4",
    "ugc_cut_b_ss": 1.5,
    "ugc_cut_b_dur": 6.5,
    "audio_asset": "/root/dressit-pipeline/assets/voice_div10_08_jokoy.mp3",
    "voiceover_script": "Leave all that family and dating stress behind. Post your favorite dress on DressIt and let sweet guys fund it for free at dressitnow.com!",
    "audio_duration_sec": 9.02,
    "caption": "What is under the couch?! 😂 Leave the stress behind: post your favorite dress on DressIt and let sweet guys fund it for $0! dressitnow.com ✨\n\n#dating #jokoy #standup #familyhumor #relatablecomedy #freedress #dressit",
    "dialogue": [
      {"start": "0:00:00.00", "end": "0:00:02.00", "text": "NORMAL PARENTS HELP"},
      {"start": "0:00:02.00", "end": "0:00:04.00", "text": "THEIR KIDS FIND STUFF\nWHEN THEY LOSE IT!"},
      {"start": "0:00:04.00", "end": "0:00:05.80", "text": "NOT MY MOM!"},
      {"start": "0:00:05.80", "end": "0:00:07.20", "text": "IF I AM LOOKING\nUNDER THE COUCH,"},
      {"start": "0:00:07.20", "end": "0:00:08.50", "text": "SHE IS RIGHT BEHIND ME:\nWHAT IS UNDER THE COUCH?!"},
      {"start": "0:00:08.70", "end": "0:00:11.20", "text": "LEAVE ALL THAT FAMILY\nAND DATING STRESS BEHIND!"},
      {"start": "0:00:11.20", "end": "0:00:13.80", "text": "POST YOUR FAVORITE DRESS\nON DRESSIT..."},
      {"start": "0:00:13.80", "end": "0:00:16.00", "text": "AND LET SWEET GUYS\nFUND IT FOR FREE!"},
      {"start": "0:00:16.00", "end": "0:00:17.50", "text": "DRESSITNOW.COM"}
    ]
  },
  {
    "number": 9,
    "id": "dglobal-batch10-div-09",
    "slug": "div10_09_ronny",
    "comedian": "Ronny Chieng",
    "title": "RELATIONSHIPS · Married 3 Times · Ronny Chieng · DressIt",
    "topic": "Asian Weddings & Getting Married 3 Times",
    "standup_clip": {
      "source_file": "/root/dressit-pipeline/source_clips/KUY907vFxyo.mp4",
      "cut1_ss": 10.8,
      "cut1_dur": 4.4,
      "cut1_crop": "crop=540:960:1320:0,scale=1080:1920:flags=lanczos",
      "cut2_ss": 15.2,
      "cut2_dur": 4.3,
      "cut2_crop": "crop=540:960:1310:0,scale=1080:1920:flags=lanczos",
      "standup_dur": 8.7,
      "setup_quote": "I love my wife so much I married her three times!",
      "punchline_quote": "Because when you have Asian parents, you have to get married in every country you have relatives in!"
    },
    "ugc_cut_a": "/root/event-hero/assets/maria_ugc/maria_04_angaevamariia_vid_28hF5F0z.mp4",
    "ugc_cut_a_ss": 1.5,
    "ugc_cut_a_dur": 3.6,
    "ugc_cut_b": "/root/event-hero/assets/maria_ugc/maria_02_angaevamariia_vid_yA0F4Nfg.mp4",
    "ugc_cut_b_ss": 2.0,
    "ugc_cut_b_dur": 7.5,
    "audio_asset": "/root/dressit-pipeline/assets/voice_div10_09_ronny.mp3",
    "voiceover_script": "Wedding season coming up and need a stunning dress? Post your wishlist on DressIt and let generous guys fund it for free at dressitnow.com!",
    "audio_duration_sec": 10.30,
    "caption": "Married the same woman three times! 💍 Wedding season coming up? Post your dream wishlist on DressIt and let generous guys fund it for $0! dressitnow.com ✨\n\n#dating #ronnychieng #standup #marriagehumor #weddingseason #freedress #dressit",
    "dialogue": [
      {"start": "0:00:00.00", "end": "0:00:02.20", "text": "I LOVE MY WIFE SO MUCH,"},
      {"start": "0:00:02.20", "end": "0:00:04.40", "text": "I MARRIED HER THREE TIMES!"},
      {"start": "0:00:04.40", "end": "0:00:06.50", "text": "BECAUSE WHEN YOU HAVE\nASIAN PARENTS,"},
      {"start": "0:00:06.50", "end": "0:00:08.70", "text": "YOU HAVE TO GET MARRIED IN EVERY\nCOUNTRY YOU HAVE RELATIVES IN!"},
      {"start": "0:00:08.90", "end": "0:00:11.50", "text": "WEDDING SEASON COMING UP\nAND NEED A STUNNING DRESS?"},
      {"start": "0:00:11.50", "end": "0:00:14.20", "text": "POST YOUR WISHLIST\nON DRESSIT..."},
      {"start": "0:00:14.20", "end": "0:00:17.00", "text": "AND LET GENEROUS GUYS\nFUND IT FOR FREE!"},
      {"start": "0:00:17.00", "end": "0:00:19.00", "text": "DRESSITNOW.COM"}
    ]
  },
  {
    "number": 10,
    "id": "dglobal-batch10-div-10",
    "slug": "div10_10_chelsea",
    "comedian": "Chelsea Handler",
    "title": "RELATIONSHIPS · Single & Not Cooking · Chelsea Handler · DressIt",
    "topic": "Single Life & Dating Standards",
    "standup_clip": {
      "source_file": "/root/dressit-pipeline/source_clips/y2cfX1vxAKY.mp4",
      "cut1_ss": 6.8,
      "cut1_dur": 5.0,
      "cut1_crop": "crop=270:480:183:0,scale=1080:1920:flags=lanczos",
      "cut2_ss": 11.8,
      "cut2_dur": 4.7,
      "cut2_crop": "crop=270:480:251:0,scale=1080:1920:flags=lanczos",
      "standup_dur": 9.7,
      "setup_quote": "I spent the day with my life partner, Ketel One, talking about why I am still single...",
      "punchline_quote": "And she had some great ideas! I do not cook, and I am not looking to learn, okay?!"
    },
    "ugc_cut_a": "/root/event-hero/assets/maria_ugc/maria_06_angaevamariia_vid_YhozXb0A.mp4",
    "ugc_cut_a_ss": 1.5,
    "ugc_cut_a_dur": 3.6,
    "ugc_cut_b": "/root/event-hero/assets/maria_ugc/maria_03_angaevamariia_vid_1hWvR6y7.mp4",
    "ugc_cut_b_ss": 2.0,
    "ugc_cut_b_dur": 8.5,
    "audio_asset": "/root/dressit-pipeline/assets/voice_div10_10_chelsea.mp3",
    "voiceover_script": "Single, fabulous, and zero intention of cooking? Post your dream outfit on DressIt and let guys who appreciate your style fund it for free at dressitnow.com!",
    "audio_duration_sec": 11.50,
    "caption": "I do not cook and I am not looking to learn! 🍸 Single, fabulous and loving it: post your dream outfit on DressIt and let guys fund it for $0! dressitnow.com ✨\n\n#dating #chelseahandler #standup #singlelife #datingstandards #freedress #dressit",
    "dialogue": [
      {"start": "0:00:00.00", "end": "0:00:02.50", "text": "I SPENT THE DAY IN BED\nWITH MY LIFE PARTNER..."},
      {"start": "0:00:02.50", "end": "0:00:05.00", "text": "KETEL ONE! TALKING ABOUT\nWHY I AM STILL SINGLE!"},
      {"start": "0:00:05.00", "end": "0:00:07.50", "text": "AND SHE HAD SOME\nREALLY GOOD IDEAS:"},
      {"start": "0:00:07.50", "end": "0:00:09.70", "text": "I DO NOT COOK, AND I AM NOT\nLOOKING TO LEARN, OKAY?!"},
      {"start": "0:00:09.90", "end": "0:00:13.00", "text": "SINGLE, FABULOUS, AND ZERO\nINTENTION OF COOKING?"},
      {"start": "0:00:13.00", "end": "0:00:16.00", "text": "POST YOUR DREAM OUTFIT\nON DRESSIT..."},
      {"start": "0:00:16.00", "end": "0:00:19.00", "text": "AND LET GUYS WHO APPRECIATE YOUR STYLE\nFUND IT FOR FREE!"},
      {"start": "0:00:19.00", "end": "0:00:21.20", "text": "DRESSITNOW.COM"}
    ]
  }
]

with open("/root/dressit-pipeline/specs_10_diverse_shorts.json", "w") as f:
    json.dump(specs, f, indent=2)
print("specs_10_diverse_shorts.json successfully written with", len(specs), "entries")
